let products = [
    { id: 1001,
            title: "Cat Food, 25lb bag",
            description: "A 25 pound bag of irresistible, organic goodness for your cat.",
            price: 2000,
            image: "Cat.jpg",
            availableInventory: 10,
            rating: 3,
        },
        { id: 1002,
            title: "Cat Food, 25lb bag",
            description: "A 25 pound bag of irresistible, organic goodness for your cat.",
            price: 2000,
            image: "Cat2.png",
            availableInventory: 10,
            rating: 3,
        },
        { id: 1003,
            title: "Cat Food, 25lb bag",
            description: "A 25 pound bag of irresistible, organic goodness for your cat.",
            price: 2000,
            image: "Cat3.png",
            availableInventory: 10,
            rating: 3,
        },
]